// ─── Mock Data for Local Deals Hub ───

export const DEALS = [
  {
    id: 1,
    name: "Biryani Feast – Large Pot",
    category: "Food",
    emoji: "🍛",
    original: 2800,
    price: 1499,
    discount: 46,
    distance: "0.3 km",
    coords: { lat: 6.9280, lng: 79.8600 },
    rating: 4.8,
    reviews: 124,
    business: "Saffron Kitchen",
    location: "Colombo 3",
    description: "Authentic Sri Lankan biryani cooked in dum style with tender chicken and aromatic basmati rice. Serves 4-5 people.",
    halal: true,
    tags: ["Dining", "Family", "Spicy"],
    saved: false,
    sponsored: false,
  },
  {
    id: 2,
    name: "Personal Training – 10 Sessions",
    category: "Gym",
    emoji: "💪",
    original: 15000,
    price: 8999,
    discount: 40,
    distance: "0.7 km",
    coords: { lat: 6.9250, lng: 79.8620 },
    rating: 4.9,
    reviews: 89,
    business: "FitLife Gym",
    location: "Nugegoda",
    description: "10 one-on-one personal training sessions with certified trainers. Includes nutrition consultation.",
    halal: true,
    tags: ["Fitness", "Health"],
    saved: true,
    sponsored: true,
  },
  {
    id: 3,
    name: "Ladies Haircut + Blowdry",
    category: "Salon",
    emoji: "✂️",
    original: 3500,
    price: 1799,
    discount: 49,
    distance: "1.1 km",
    coords: { lat: 6.9300, lng: 79.8550 },
    rating: 4.7,
    reviews: 203,
    business: "Glamour Studio",
    location: "Bambalapitiya",
    description: "Premium haircut and blowdry by senior stylists. Includes hair wash and scalp massage.",
    halal: true,
    tags: ["Beauty", "Women"],
    saved: false,
    sponsored: false,
  },
  {
    id: 4,
    name: "O/L Maths – Monthly Tuition",
    category: "Tuition",
    emoji: "📚",
    original: 5000,
    price: 2999,
    discount: 40,
    distance: "0.5 km",
    coords: { lat: 6.9100, lng: 79.8700 },
    rating: 4.9,
    reviews: 312,
    business: "Bright Minds Academy",
    location: "Dehiwala",
    description: "Comprehensive O/Level Mathematics tuition with experienced teachers. Small batch sizes, exam practice.",
    halal: true,
    tags: ["Education", "Students"],
    saved: false,
    sponsored: false,
  },
  {
    id: 5,
    name: "Kottu Roti – Family Pack",
    category: "Food",
    emoji: "🫔",
    original: 1800,
    price: 999,
    discount: 44,
    distance: "0.2 km",
    coords: { lat: 6.9200, lng: 79.8800 },
    rating: 4.6,
    reviews: 456,
    business: "Roti King",
    location: "Borella",
    description: "Freshly made chicken kottu roti family pack. Serves 3-4 people. Choose your spice level.",
    halal: true,
    tags: ["Dining", "Quick Bite"],
    saved: true,
    sponsored: false,
  },
  {
    id: 6,
    name: "Yoga Class – Monthly Pass",
    category: "Gym",
    emoji: "🧘",
    original: 6000,
    price: 3499,
    discount: 42,
    distance: "1.4 km",
    coords: { lat: 6.9400, lng: 79.8600 },
    rating: 4.8,
    reviews: 67,
    business: "Zen Studio",
    location: "Colombo 7",
    description: "Unlimited yoga classes for one month. All levels welcome. Includes meditation sessions.",
    halal: true,
    tags: ["Wellness", "Fitness"],
    saved: false,
    sponsored: false,
  },
  {
    id: 7,
    name: "Facials & Skin Care Package",
    category: "Salon",
    emoji: "💆",
    original: 8000,
    price: 4499,
    discount: 44,
    distance: "0.9 km",
    coords: { lat: 6.8950, lng: 79.8750 },
    rating: 4.7,
    reviews: 88,
    business: "Glow Up Spa",
    location: "Wellawatte",
    description: "Full skin care package including deep cleansing facial, moisturizing treatment, and eyebrow threading.",
    halal: true,
    tags: ["Beauty", "Wellness"],
    saved: false,
    sponsored: true,
  },
  {
    id: 8,
    name: "A/L Science – Crash Course",
    category: "Tuition",
    emoji: "🔬",
    original: 12000,
    price: 6999,
    discount: 42,
    distance: "2.1 km",
    coords: { lat: 6.9000, lng: 79.8900 },
    rating: 4.9,
    reviews: 145,
    business: "Scholar's Hub",
    location: "Kandy Road",
    description: "3-week A/Level Science crash course covering Physics, Chemistry & Biology. Past papers included.",
    halal: true,
    tags: ["Education", "Exam Prep"],
    saved: false,
    sponsored: false,
  },
  {
    id: 9,
    name: "Short Eats Combo – 20 Pcs",
    category: "Food",
    emoji: "🥟",
    original: 1200,
    price: 749,
    discount: 38,
    distance: "0.1 km",
    coords: { lat: 6.9271, lng: 79.8650 },
    rating: 4.5,
    reviews: 289,
    business: "Ceylon Bakers",
    location: "Maradana",
    description: "A mix of 20 freshly baked short eats including cutlets, patties, and rolls.",
    halal: true,
    tags: ["Snacks", "Quick Bite"],
    saved: false,
    sponsored: false,
  },
  {
    id: 10,
    name: "Swimming Lessons – 8 Sessions",
    category: "Sports",
    emoji: "🏊",
    original: 8000,
    price: 4999,
    discount: 38,
    distance: "1.8 km",
    coords: { lat: 6.8900, lng: 79.8500 },
    rating: 4.8,
    reviews: 52,
    business: "AquaFit Pool",
    location: "Colombo 5",
    description: "8 swimming lessons for beginners and intermediate. Certified instructors, lifeguard on duty.",
    halal: true,
    tags: ["Sports", "Kids", "Adults"],
    saved: false,
    sponsored: false,
  },
];

export const CATEGORIES = [
  { id: "all", label: "All", emoji: "🌟" },
  { id: "food", label: "Food", emoji: "🍛", color: "#FF6B6B" },
  { id: "gym", label: "Gym", emoji: "💪", color: "#7C3AED" },
  { id: "salon", label: "Salon", emoji: "✂️", color: "#EC4899" },
  { id: "tuition", label: "Tuition", emoji: "📚", color: "#0EA5E9" },
  { id: "sports", label: "Sports", emoji: "⚽", color: "#10B981" },
  { id: "events", label: "Events", emoji: "🎉", color: "#F59E0B" },
  { id: "travel", label: "Travel", emoji: "✈️", color: "#3B82F6" },
];

export const INFLUENCERS = [
  {
    id: 1,
    name: "Ayesha Malik",
    handle: "@ayesha.slk",
    emoji: "👩",
    followers: "124K",
    deals: 48,
    commission: 12,
    verified: true,
    referralCode: "AYESHA20",
    bio: "Lifestyle & Food blogger based in Colombo. Sharing the best halal deals!",
    speciality: "Food & Lifestyle",
    rating: 4.9,
  },
  {
    id: 2,
    name: "Imran Hassan",
    handle: "@imranfit",
    emoji: "👨",
    followers: "89K",
    deals: 36,
    commission: 10,
    verified: true,
    referralCode: "IMRAN15",
    bio: "Fitness influencer & certified PT. Best gym deals in Colombo and suburbs.",
    speciality: "Fitness & Wellness",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Fatima Zara",
    handle: "@fatimazara",
    emoji: "🧕",
    followers: "67K",
    deals: 29,
    commission: 8,
    verified: true,
    referralCode: "FATIMA10",
    bio: "Beauty & fashion creator. Modest fashion meets amazing beauty deals.",
    speciality: "Beauty & Fashion",
    rating: 4.7,
  },
  {
    id: 4,
    name: "Rizwan Khan",
    handle: "@rizwantravels",
    emoji: "🧔",
    followers: "45K",
    deals: 22,
    commission: 9,
    verified: false,
    referralCode: "RIZWAN10",
    bio: "Travel & events enthusiast exploring Sri Lanka's best experiences.",
    speciality: "Travel & Events",
    rating: 4.6,
  },
  {
    id: 5,
    name: "Sara Noor",
    handle: "@saranoor.edu",
    emoji: "👩‍🎓",
    followers: "38K",
    deals: 18,
    commission: 7,
    verified: true,
    referralCode: "SARA15",
    bio: "Education advocate helping students find the best tuition deals.",
    speciality: "Education",
    rating: 4.8,
  },
  {
    id: 6,
    name: "Ahmed Rashid",
    handle: "@ahmedrashid",
    emoji: "🧑",
    followers: "29K",
    deals: 14,
    commission: 6,
    verified: false,
    referralCode: "AHMED10",
    bio: "Tech & lifestyle creator. Finding value in every deal.",
    speciality: "Tech & Lifestyle",
    rating: 4.5,
  },
];

export const CHALLENGES = [
  {
    id: 1,
    icon: "🛒",
    name: "First Purchase",
    desc: "Complete your first deal purchase",
    pts: 100,
    progress: 100,
    completed: true,
  },
  {
    id: 2,
    icon: "📸",
    name: "Social Sharer",
    desc: "Share 3 deals on social media",
    pts: 150,
    progress: 66,
    completed: false,
  },
  {
    id: 3,
    icon: "👥",
    name: "Refer a Friend",
    desc: "Invite a friend using your referral code",
    pts: 200,
    progress: 0,
    completed: false,
  },
  {
    id: 4,
    icon: "⭐",
    name: "Top Reviewer",
    desc: "Leave 5 reviews on purchased deals",
    pts: 250,
    progress: 40,
    completed: false,
  },
  {
    id: 5,
    icon: "🔥",
    name: "Deal Streak",
    desc: "Purchase deals 5 days in a row",
    pts: 500,
    progress: 20,
    completed: false,
  },
];

export const LEADERBOARD = [
  { rank: 1, name: "Ayesha M.", emoji: "👩", pts: 8420 },
  { rank: 2, name: "Imran H.", emoji: "👨", pts: 7210 },
  { rank: 3, name: "Sara N.", emoji: "👩‍🎓", pts: 6580 },
  { rank: 4, name: "Ahmed R.", emoji: "🧑", pts: 5999 },
  { rank: 5, name: "Fatima Z.", emoji: "🧕", pts: 5340 },
  { rank: 6, name: "You", emoji: "🌟", pts: 1240, isUser: true },
];

export const NOTIFICATIONS = [
  {
    id: 1, icon: "🔥", title: "Hot Deal Alert!", msg: "50% off Biryani at Saffron Kitchen – ends tonight!", unread: true, time: "2m ago",
  },
  {
    id: 2, icon: "⭐", title: "Points Earned", msg: "You earned 150 points from your last purchase.", unread: true, time: "1h ago",
  },
  {
    id: 3, icon: "👥", title: "New Follower", msg: "Ayesha Malik started following your activity.", unread: true, time: "3h ago",
  },
  {
    id: 4, icon: "🎉", title: "Challenge Complete!", msg: "You completed the 'First Purchase' challenge.", unread: false, time: "1d ago",
  },
  {
    id: 5, icon: "💬", title: "New Deal Near You", msg: "FitLife Gym added a new personal training deal.", unread: false, time: "2d ago",
  },
];

export const STORIES = [
  { id: 1, label: "Saffron", emoji: "🍛", seen: false },
  { id: 2, label: "FitLife", emoji: "💪", seen: false },
  { id: 3, label: "Ayesha", emoji: "👩", seen: false },
  { id: 4, label: "Glamour", emoji: "✂️", seen: true },
  { id: 5, label: "Imran", emoji: "👨", seen: true },
  { id: 6, label: "Scholar", emoji: "📚", seen: true },
];

export const TRANSLATIONS = {
  en: {
    appName: "Local Deals Hub",
    tagline: "Best Deals Near You",
    home: "Home",
    explore: "Explore",
    influencers: "Influencers",
    rewards: "Rewards",
    profile: "Profile",
    search: "Search deals, shops...",
    nearbyDeals: "Nearby Deals",
    trendingNow: "Trending Now",
    topInfluencers: "Top Influencers",
    seeAll: "See all",
    login: "Login",
    register: "Register",
    welcomeBack: "Welcome back!",
    createAccount: "Create Account",
    email: "Email",
    password: "Password",
    phone: "Phone Number",
    name: "Full Name",
    orContinueWith: "Or continue with",
    points: "Points",
  },
  si: {
    appName: "ලෝකල් ඩීල්ස් හබ්",
    tagline: "ඔබ ළඟ හොඳම ඩීල්",
    home: "මුල් පිටුව",
    explore: "සොයන්න",
    influencers: "ඉන්ෆ්ලූඑන්සර්ස්",
    rewards: "ත්‍යාග",
    profile: "ගිණුම",
    search: "ඩීල් සොයන්න...",
    nearbyDeals: "ළඟ ඇති ඩීල්",
    trendingNow: "දැන් ට්‍රෙන්ඩ් වේ",
    topInfluencers: "ඉහළ ඉන්ෆ්ලූඑන්සර්ස්",
    seeAll: "සියල්ල",
    login: "ලොගින්",
    register: "ලියාපදිංචි",
    welcomeBack: "නැවත සාදරයෙන් පිළිගනිමු!",
    createAccount: "ගිණුමක් සාදන්න",
    email: "ඊමේල්",
    password: "මුරපදය",
    phone: "දුරකථන අංකය",
    name: "සම්පූර්ණ නම",
    orContinueWith: "හෝ ඉදිරියට",
    points: "පොයින්ට්",
  },
  ta: {
    appName: "லோக்கல் டீல்ஸ் ஹப்",
    tagline: "உங்களுக்கு அருகில் சிறந்த டீல்கள்",
    home: "முகப்பு",
    explore: "ஆராயுங்கள்",
    influencers: "இன்ஃப்ளூயென்சர்கள்",
    rewards: "வெகுமதிகள்",
    profile: "சுயவிவரம்",
    search: "டீல்களை தேடுங்கள்...",
    nearbyDeals: "அருகில் உள்ள டீல்கள்",
    trendingNow: "இப்போது ட்ரெண்டிங்",
    topInfluencers: "சிறந்த இன்ஃப்ளூயென்சர்கள்",
    seeAll: "அனைத்தும்",
    login: "உள்நுழைவு",
    register: "பதிவு",
    welcomeBack: "மீண்டும் வருக!",
    createAccount: "கணக்கு உருவாக்குங்கள்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    phone: "தொலைபேசி எண்",
    name: "முழு பெயர்",
    orContinueWith: "அல்லது தொடரவும்",
    points: "புள்ளிகள்",
  },
};
